"""manual points, decimal points, optional join date

Revision ID: a180ce688a3b
Revises: 73903ed8fdc2
Create Date: 2026-09-23 20:35:54.161547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a180ce688a3b'
down_revision = '73903ed8fdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('joined_on',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('joined_on',
               existing_type=sa.DATE(),
               nullable=False)

    op.drop_table('manual_points')
    # ### end Alembic commands ###
